# platform :ios, '8.0'

target 'ZPOperator' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'AFNetworking'
  pod 'MJRefresh'
  pod 'SDWebImage'

  # Pods for ZPOperator

end
